### ISSUE TITLE
Reverse bytes for x360

### ISSUE THREAD

**Issue by metalex10** [mrazza/gonav#1]
It's possible create a tool for reverse bytes for x360?

**Comment by mrazza** [comment]
What is the ask here? Are you saying that the xbox 360 nav meshes are encoded with a different endianness? I do not have access to those files and cannot make the change but feel free to submit a PR.

**Comment by metalex10** [comment]
yes, is encoded in different endian, for example if pc is uint32  in xbox360 is reversed uint32
pc 10000000
xbox 00000010
for 32 bits


pc 64989829
xbox 98296498

for 64 bits

what I need is a .go instead of reading or writing like this is the other way round, since I've already converted the textures to the .bsp but I'm missing the .nav

**Comment by metalex10** [comment]
check this http://www.csharp-examples.net/reverse-bytes/

I mention it to you because I did not move in .go files and I do not know how I could do it when I read it, I wrote it in a new file but already invested

**Comment by metalex10** [comment]
or check this please 
https://stackoverflow.com/questions/105252/how-do-i-convert-between-big-endian-and-little-endian-values-in-c

**Comment by mrazza** [comment]
If non-PC parsing is important, please send a pull request with some coherent API. I cannot validate this behavior and have no plans to support.
